### PR TITLE
Change proposal drawer fixed

### LINKED ISSUE #86: Change proposal preview is broken

### PR DESCRIPTION
**Pull request by Daniilmass**
Resolves #86

### CODE REVIEW

File: src/hooks/api-queries.ts [hunk 1]
```diff
@@ -321,6 +321,29 @@ export const useListTasksQuery = ({ projectId, milestoneId, first, max }: ListTa
...
+ * Lists tasks affected by a change proposal
+ *
+ * @param changeProposalId change proposal id
+ */
+export const useListChangeProposalAffectedTasksQuery = (changeProposalId?: string) => {
+  const { tasksApi } = useApi();
+  const { t } = useTranslation();
+
+  return useQuery({
+    queryKey: ["changeProposalTasks", changeProposalId],
```
Comment (lauriLukkarinen) [inline src/hooks/api-queries.ts:334]: It would be better to directly use useListTasks, as it would then share the correct query key and parameters.

File: src/components/tasks/change-proposals-drawer.tsx [hunk 2]
```diff
@@ -54,6 +55,14 @@ const ChangeProposalsDrawer = ({
     [changeProposals],
   );
 
+  // Clears selected change proposal id when drawer is closed
+  useEffect(() => {
```
Comment (lauriLukkarinen) [inline src/components/tasks/change-proposals-drawer.tsx:59]: It would be easier to handle this in click event handler, like

```
const onToggleOpen = () => {
  if (open) setSelectedChangeProposalId("");
  setOpen(!open);
}
```

**Review by lauriLukkarinen — CHANGES_REQUESTED** [review]

File: src/hooks/api-queries.ts [hunk 3]
```diff
@@ -303,15 +303,16 @@ export const useFindProjectMilestoneQuery = ({ projectId, milestoneId }: FindPro
...
  */
-export const useListTasksQuery = ({ projectId, milestoneId, first, max }: ListTasksRequest) => {
+export const useListTasksQuery = (params: Partial<ListTasksRequest>) => {
+  const { projectId, changeProposalId, milestoneId, first, max } = params;
   const { tasksApi } = useApi();
   const { t } = useTranslation();
 
   return useQuery({
-    queryKey: ["tasks", { milestoneId, first, max }],
+    queryKey: ["projects", projectId, "tasks", { changeProposalId, milestoneId, first, max }],
```
Comment (lauriLukkarinen) [inline src/hooks/api-queries.ts:312]: Is tasks still under projects? If not, this should be
`["tasks", { projectId, milestoneId, changeProposalId, first, max }]`

**Review by lauriLukkarinen — CHANGES_REQUESTED** [review]

**Review by lauriLukkarinen — APPROVED** [review]
